// GENERATED by docs/latent-forge/extract_help.mjs -- do not edit by hand.
// Source: docs/sa3-studio/design_handoff/SA3 Studio v3.dc.html (80 data-help strings).
// Regenerate with `npm run help:extract` from latent-forge/.
//
// Spec §9.4: strings describing behaviour this backend does not have are rewritten, and
// each one is preceded by a comment naming the original, tagged handoff: and quoted.

export type HelpId =
  | "session"
  | "model"
  | "modelEpoch"
  | "modelFolder"
  | "masterPreset"
  | "renderButton"
  | "helpToggle"
  | "masterStrip"
  | "projectBpm"
  | "snapMode"
  | "matchBpm"
  | "matchDownbeats"
  | "zoomHint"
  | "ruler"
  | "laneHeader"
  | "laneDropSlot"
  | "laneTarget"
  | "clipBpm"
  | "clipDetune"
  | "mixFold"
  | "mixOrder"
  | "mixNodeT"
  | "signalPath"
  | "mixExpand"
  | "chromaMatchMarks"
  | "chromaChord"
  | "chromaMatchLegend"
  | "chromaDetuneScan"
  | "chromaBestCriterion"
  | "chromaBest"
  | "chromaHeatmap"
  | "chromaMatchCurve"
  | "targetBar"
  | "promptPreset"
  | "a2aToggle"
  | "a2aNoise"
  | "prompt"
  | "negativePrompt"
  | "modelStagePost"
  | "modelStageBase"
  | "steps"
  | "cfg"
  | "length"
  | "seed"
  | "seedRandom"
  | "sigmaGraph"
  | "sidePaneToggle"
  | "overlapChromaXfade"
  | "overlapOverride"
  | "overlapSteps"
  | "overlapCfg"
  | "filesRow"
  | "generationRenderButton"
  | "modulePreset"
  | "latchHead"
  | "latchTargetKind"
  | "latchTargetValue"
  | "latchTargetFrom"
  | "latchWeight"
  | "latchStartPct"
  | "latchEndPct"
  | "latchRho"
  | "latchMu"
  | "latchGamma"
  | "latchMeanIter"
  | "latchLogNorms"
  | "bungeeSemitones"
  | "cfgLo"
  | "cfgHi"
  | "cfgUnit"
  | "sampler"
  | "scheduleShape"
  | "scheduleRho"
  | "lamMin"
  | "lamMax"
  | "sigmaMin"
  | "sigmaMax"
  | "stepped"
  | "tilt"
  | "plateaus"
  | "rescale"
  | "latentNormalise"
  | "transportPlay"
  | "transportStop"
  | "transportLoop"
  | "darkToggle"
  | "filmTarget"
  | "opSelect"
  | "previewMixdownToggle"
  | "mixdownCommit"
  | "mixdownWave"
  | "previewRender"
  | "previewHistory"
  | "previewDragToLane"
  | "previewUseSettings"
  | "previewReplaceClip"
  | "latchToggle"
  | "filmToggle"
  | "filmPreset"
  | "filmScale"
  | "loraToggle"
  | "loraPreset"
  | "loraModel"
  | "loraScale"
  | "bungeeToggle"
  | "bungeePreset"
  | "filmCkpt"
  | "modulePresetSave"
  | "modulePresetDelete"
  | "masterLatchToggle"
  | "masterLatchHeadLabel"
  | "masterHead"
  | "masterGain"
  | "mixQuadWeight"
  | "mixLerp"
  | "mixSlerp"
  | "filesRoot"
  | "filesFilter"
  | "masterPresetSave"
  | "sessionSave"
  | "sessionImportV1"
  | "mixdownButton"
  ;

export const HELP: Record<HelpId, string> = {
  session: "Session — clips rendered in one working session.",
  // handoff: "Checkpoint used for generation, a2a, inpainting and the encode/decode round trip."
  model: "Checkpoint used for generation, a2a, inpainting and the encode/decode round trip. The first four entries are backbones and switching one rebuilds the model; the rest are adapters and set the session's default checkpoint path.",
  modelEpoch: "Which saved epoch of the selected adapter run to load, newest first. Shown as the epoch number and the training step. Picking another epoch sets the session's default checkpoint path, the same as picking the run.",
  modelFolder: "Direct checkpoint folder — any path the loader can read.",
  masterPreset: "Master preset — every lane chain, the clip layout, mix order and node values, master chain, sigma schedule and prompt in one recall.",
  renderButton: "Runs the current target. While sampling, the window border runs a C64 loader raster bar whose sweep rate falls with the remaining step count.",
  helpToggle: "Help mode. While on, hovering a control shows what it does.",
  masterStrip: "Master strip: the decoded mix result. The purple curve is the a2a noise-amount envelope over time.",
  projectBpm: "Project tempo. Every clip is stretched from its native BPM to this, and the grid is drawn from it. Safe value: MATCH BPM sets it to the mean of the loaded clips, which is the least stretch for all of them. Drag to scale; hold shift for 1/100th detail.",
  snapMode: "Snap resolution for dragging clips. DOWNBEATS is magnetic — a dragged clip's downbeats jump to another clip's within 5px, and dragging further pulls them free again. CLIP EDGES snaps to the start or end of any clip.",
  matchBpm: "Least-work tempo match: the clips meet at their mean native BPM, so each is stretched as little as possible. Does not move anything in time.",
  matchDownbeats: "Shifts every clip by the shortest path so its downbeats land on the common downbeat phase — the circular mean of all clips' phases. Tempo is left alone.",
  zoomHint: "Middle-click and drag over the timeline: up and down zooms, left and right scrolls, both at once in one gesture. Shift + wheel also scrolls. Plain wheel is left to the page.",
  ruler: "Ruler: bars and beats, seconds, and latent frames at 10.767 Hz. Click to locate the playhead. Middle-click and drag to zoom (up/down) and scroll (left/right) at once.",
  laneHeader: "Lane header. Click to make this lane the active chain in the context pane; TARGET makes it the chroma reference the other lanes are matched against.",
  laneDropSlot: "Drop an audio file or a latent here to add a clip at the playhead. Latents are decoded for display; the chain re-encodes them before mixing.",
  laneTarget: "Make this lane the chroma target. Every other lane is then coloured by how consonant it is with this one.",
  clipBpm: "Native BPM of the selected clip in this lane. Correcting it restretches that clip against the project tempo. Drag to scale; hold shift for 1/100th detail.",
  clipDetune: "Pitch offset of the selected clip in cents. It rotates the clip's chroma against the target, so dragging it sweeps the match score — useful for finding where a blues or a differently tuned source actually sits. 100 cents is one semitone. Safe value: 0. Drag to scale.",
  mixFold: "Fold the mix order and signal path into a one-line summary to free vertical space.",
  mixOrder: "slerp is defined pairwise, so a 4-way mix runs as a tree of pairwise slerps. WEIGHTED 4-WAY mixes all four lanes at once but is lerp-only.",
  mixNodeT: "Interpolation position between this node's two inputs: 0 is all of the first, 1 all of the second. Safe value: 0.50.",
  signalPath: "Live signal path: stages reflect what the clips and chains currently do. Dimmed stages are skipped for this run.",
  mixExpand: "Expand the mix order and signal path panels.",
  chromaMatchMarks: "Per-frame harmonic-overlap score against the target. The three marks are computed from the target itself: what the score reads when the same chroma is heard a tritone, a fifth, and a unison away. Anything at or above the fifth mark reads as in tune with the target; below the tritone mark is genuinely clashing.",
  chromaChord: "Type a chord symbol (e.g. Cmaj7, F#m, Adim) and the key row fills in.",
  chromaMatchLegend: "Match is a harmonic-overlap score: the partial series implied by each chroma frame is compared with the target's, so a fifth scores high and a semitone low even though it is closer in pitch.",
  chromaDetuneScan: "Match score as the selected clip is detuned across ±100 cents. The peak is where this clip's chroma lines up best with the target; the red mark is the clip's current detune. Click or drag on the strip to set it, or press BEST to jump to the peak.",
  chromaBestCriterion: "What BEST optimises. HIGHEST takes the detune with the greatest average match — the curve sits high but may still swing. STEADIEST takes the greatest average minus its spread, so the match holds level through the clip, which is what matters before a crossfade or an inpainted join. A flat curve on its own is not a good match: it can be uniformly dissonant.",
  chromaBest: "Sets the clip's detune to the peak of the scan, under the criterion in the button to the left.",
  chromaHeatmap: "Chroma over time for the selected lane, with the target's chroma as the reference row at the top. Per-frame colour is the harmonic-overlap score when CONSONANCE COLOUR is on. Moving the cursor reads out the pitch class under it and marks the same frame on the clip in the lane with a red line.",
  chromaMatchCurve: "Harmonic-overlap score over time against the target, overlaid on the heatmap. Dips are dissonant passages.",
  targetBar: "These settings act on whatever is selected: a clip (audio→audio on that clip), an inpaint region, or nothing (a fresh render). Selecting something else switches the whole pane with it, so a prompt always belongs to one target.",
  promptPreset: "Prompt preset — recalls the prompt and negative prompt text only.",
  a2aToggle: "Audio→audio on this clip: it is decoded, re-noised to the amount below, and re-denoised with these settings. Off means the clip is left as it is and the settings apply to a fresh render. Safe value: off.",
  // handoff: "Init noise level — how much of the clip is destroyed before re-denoising. Near 0 barely changes it; at the top it is a fresh generation with only a hint of the source. The backend range is 0.1–100 for v/eps models and 0.01–1.0 for rectified flow. Safe value: 0.2. Drag to scale."
  a2aNoise: "Init noise level — how much of the clip is destroyed before re-denoising. Near 0 barely changes it; at the top it is a fresh generation with only a hint of the source. The range here is 0–1 throughout: SA3 is rectified flow, so the far wider v/eps noise scale does not apply. Safe value: 0.4. Drag to scale.",
  prompt: "Conditioning prompt for generation, a2a and inpainting. Empty means unconditional.",
  negativePrompt: "Negative conditioning — guidance is steered away from this. Empty falls back to the unconditional embedding.",
  // handoff: "The released SA3 checkpoints are adversarially post-trained: they sample with ping-pong in 8 steps on a logSNR-uniform schedule and need no CFG, because guidance is baked in during distillation. Safe value: POST."
  modelStagePost: "POST is the released, adversarially post-trained checkpoint: ping-pong in 8 steps on a logSNR-uniform schedule and no CFG, because guidance is baked in during distillation. It is the resident model here. Safe value: POST.",
  // handoff: "The flow-matching base model before distillation: solved as an ODE over 50–100 steps with DPM++ and real CFG. Only use this if you are running a pre-distillation checkpoint. Safe value: POST."
  modelStageBase: "BASE is the flow-matching model before distillation: euler over about 24 steps with real CFG. Switching stage reloads the backbone on the render server and takes roughly a minute, so it asks before it does. Safe value: POST.",
  // handoff: "Number of denoising steps. More steps cost time and give diminishing returns. Safe value: 100 for v/eps models, 50 for rectified_flow, 8 for rf_denoiser. Drag to scale; hold shift for 1/100th detail."
  steps: "Number of denoising steps. More steps cost time and give diminishing returns. Safe value: 8 for POST — the released checkpoints are distilled to sample in eight — and 24 for BASE. Drag to scale; hold shift for 1/100th detail.",
  // handoff: "Classifier-free guidance scale — how hard the prompt is enforced. Too high burns the output and flattens dynamics. Safe value: 7.0 (1.0 for rf_denoiser, which is effectively guidance-free). Drag to scale; hold shift for 1/100th detail."
  cfg: "Classifier-free guidance scale — how hard the prompt is enforced. Too high burns the output and flattens dynamics. POST ignores it: guidance is distilled into the checkpoint, so the field greys out and 1.0 is sent. Range 0–64. Safe value: 6.0 on BASE.",
  // handoff: "Requested duration. This is not just a buffer size — SA3 conditions on it through both cross-attention and AdaLN, and allocates a variable-length latent of ceil((d + 6 s) · 44100 / 4096) embeddings, the trailing 6 s being silence padding that is trimmed after generation. Ceiling is the checkpoint's own maximum (2 min for small, 6 min 20 s for medium and large). Safe value: anything under that. Drag to scale."
  length: "Requested duration. This is not just a buffer size — SA3 conditions on it through both cross-attention and AdaLN, and allocates a variable-length latent of ceil((d + 6 s) · 44100 / 4096) embeddings, the trailing 6 s being silence padding that is trimmed after generation. A forge pass is capped at 184 s, which is what the display card holds; longer arrangements are built from several clips. Safe value: anything under 184 s. Drag to scale.",
  seed: "RNG seed for the initial noise. Same seed, same settings, same result. Safe value: any integer, or RND for a fresh one — there is no wrong seed.",
  seedRandom: "New random seed.",
  sigmaGraph: "Sigma over the sampler steps, with a tick per step — where the ticks bunch up, more steps are spent in that noise band. The turquoise band is the interval where CFG is applied.",
  sidePaneToggle: "Collapse or expand the context pane. Menus keep a lit marker when something inside them is active.",
  overlapChromaXfade: "Crossfades the chroma of the two clips through the overlap using the harmonic-overlap matching, instead of a plain amplitude fade.",
  overlapOverride: "When off, the region is inpainted with the global STEPS and CFG from the pane below. Safe value: off.",
  overlapSteps: "Steps used for this inpaint region only, overriding the global STEPS. Short regions need fewer. Safe value: leave the override off, or 28. Drag to scale; hold shift for 1/100th detail.",
  overlapCfg: "Guidance scale for this inpaint region only. Lower than the global value usually blends better, since the region has to agree with audio on both sides. Safe value: 3.0. Drag to scale; hold shift for 1/100th detail.",
  filesRow: "Drag onto a lane to add a clip at the playhead. Audio and latents are both accepted.",
  generationRenderButton: "Renders with the prompt and settings from the pane at the bottom of the screen. While sampling, the window border runs a raster bar whose sweep rate falls with the remaining step count.",
  modulePreset: "Module preset — recalls just this module's settings.",
  latchHead: "LatCH head checkpoint, listed from latch_weights/*.pt. The target slider's bounds come from the head's own feature_stats / p1–p99 metadata.",
  // handoff: "Target kind. constant holds one value; ramp_up / ramp_down sweep it over the window; beat_grid takes a BPM instead of a feature value; chroma_major / chroma_minor target a key."
  latchTargetKind: "Target kind. constant holds one value; ramp_up / ramp_down sweep it over the window; beat_grid takes a BPM instead of a feature value. chroma_major and chroma_minor are not offered here — chroma is matched against the TARGET lane in the CHROMA tab instead.",
  latchTargetValue: "The value this head steers the feature toward, in the feature's own unit (dB for the rms heads, BPM for beat_grid). The slider spans the head's training mean ± 2 standard deviations, so mid-slider is roughly the training mean; a typed value may go outside it, and the readout beside it gives the distance from the mean in standard deviations (σ). A target several σ out is not a target the head was trained on. For a ramp this is where the ramp ends. Safe value: the head's mean, or 120 BPM for beat_grid.",
  latchTargetFrom: "Where a ramp starts, in the same unit as the target. The ramp runs from this value to TARGET across the whole clip, in the head's own range; the sampler's built-in ramp starts from 0, which for a head such as hardness (mean 66) is about 19σ outside anything it was trained on and drives the render to noise. Untouched, a ramp keeps that old 0 start.",
  // handoff: "How much this slot contributes relative to the other. 0 disables the slot without unloading it; past roughly 10 the head tends to dominate the prompt. Safe value: 1.0."
  latchWeight: "How much this slot contributes. 0 disables the slot without unloading it. The strength actually applied is ρ (and μ) × the head's default gain (512) × this weight, and the readout beside the slider shows it. Each head has its own limit past which the output breaks up (eval/latch_bracket_quality.json, the lowest of the goa and ambient test prompts, at ρ = 1): most heads stay clean to weight 16, rms_energy_air to 1 and spectral_flatness to 1, hardness only to 0.25 -- it broke up at weight 1 on goa. The slider is not linear, so the low end has room; the marker on the slider is the head's limit. The two slots are summed, and the result applies to this lane's latent only. Safe value: 1.0, or the head's limit if that is lower.",
  latchStartPct: "Window start as a fraction of the step schedule. Each slot gets its own colour and its own lane on the sigma graph; hatching marks where the window overlaps the CFG-active region.",
  latchEndPct: "Window end as a fraction of the step schedule. Guidance late in the schedule fights the detail steps, so keeping the window early is usually better. Safe value: 0.20.",
  // handoff: "Weight on the variance term of the LatCH guidance objective — how strongly the latent's spread is pushed toward the head's target. High values wash out transients. Safe value: 1.0."
  latchRho: "Weight on the variance term of the LatCH guidance objective — how strongly the latent's spread is pushed toward the head's target. High values wash out transients. This is a lane chain setting, applied before the mix, so raising it on one lane leaves the others alone. Safe value: 1.0.",
  // handoff: "Weight on the mean term — how strongly the latent's centre is moved toward the target. This is the one that actually shifts the feature; raise it before ρ. Safe value: 1.0."
  latchMu: "Weight on the mean term — how strongly the latent's centre is moved toward the target. This is the one that actually shifts the feature; raise it before ρ. Like ρ it belongs to this lane's chain. Safe value: 1.0.",
  latchGamma: "Noise injected per guidance iteration, which keeps the correction from collapsing into a single mode. 0 makes it deterministic and often over-smoothed. Safe value: 0.3.",
  latchMeanIter: "Inner iterations spent solving the mean term at each step. More is more faithful and linearly slower. Safe value: 4.",
  latchLogNorms: "Prints the guidance gradient norms to the terminal each step — diagnostic only, for checking whether ρ and μ are in a sane range. Safe value: off.",
  bungeeSemitones: "Pitch shift in semitones, applied during the Bungee stage before re-encoding. Safe value: 0 — no shift. Drag to scale; hold shift for 1/100th detail.",
  cfgLo: "Where guidance switches on, in progress (1 − sigma) as the sampler reports it — not a step fraction. Raising it leaves the first, structure-forming steps unguided. Safe value: 0.00. Drag to scale; hold shift for 1/100th detail.",
  cfgHi: "Where guidance switches off, in progress (1 − sigma). Lowering it lets the final detail steps run unguided, which often reduces harshness. Safe value: 1.00. Drag to scale; hold shift for 1/100th detail.",
  cfgUnit: "Switch the CFG interval display between progress (0–1, the value the backend takes) and the step number where that progress is first crossed. It is stored as progress, so changing STEPS only changes the displayed step numbers.",
  // handoff: "Which sampler integrates the reverse diffusion. The list follows the model's objective: rectified_flow gives euler / rk4 / dpmpp, rf_denoiser gives pingpong, the v and eps models give the k-diffusion set. Safe value: dpmpp-3m-sde (euler for rectified_flow, pingpong for rf_denoiser)."
  sampler: "Which sampler integrates the reverse diffusion. SA3 is rectified flow, so the list is euler / rk4 / dpmpp / pingpong on BASE and pingpong / euler on POST; the k-diffusion samplers are not offered. LatCH guidance forces euler while it is on. Safe value: euler on BASE, pingpong on POST.",
  // handoff: "How sigma falls from σ MAX to σ MIN. GEOMETRIC is the one the backend's three numbers describe; the others must be sent as an explicit sigma array. LINEAR falls evenly in sigma, so it lingers at low noise. LOG drops fast then flattens — more steps on detail. EXPONENTIAL holds high noise then dives — more steps on structure. COSINE is a smooth S. Safe value: logSNR-uniform for the released checkpoints. STEPPED beside PLATEAUS then holds any of these shapes in plateaus and jumps down between them."
  scheduleShape: "How sigma falls across the steps. MODEL is the checkpoint's own schedule and the safe default; LOGSNR is uniform in log-SNR, which is what the released checkpoints ship with; GEOMETRIC is the backend's three-number ramp; LINEAR lingers at low noise, LOG spends more steps on detail, EXPONENTIAL more on structure, COSINE is a smooth S. Every shape but MODEL reaches the server as an explicit sigma array. STEPPED beside PLATEAUS holds any of these shapes in plateaus and jumps down between them. Safe value: MODEL.",
  scheduleRho: "Sigma curve strength: how the steps are distributed between σ MAX and σ MIN. 1.0 is a plain geometric ramp; higher values spend more steps at high noise, lower values crowd them at the low-noise end where detail is decided. Watch the tick density on the graph. Safe value: 1.0. Drag to scale; shift for 1/100th.",
  lamMin: "Low end of the logSNR interval — the noisiest step the schedule starts from. SA3 ships −6.2. Safe value: −6.2. Drag to scale.",
  lamMax: "High end of the logSNR interval — the cleanest step the schedule ends at. SA3 ships 2.0. Safe value: 2.0. Drag to scale.",
  // handoff: "The noise level the schedule ends at, just before the final step, in the same unitless multiples of the latent's standard deviation as σ MAX. Too high and the output stays hazy; effectively zero and the last steps do nothing. Ignored by rectified-flow objectives. Safe value: 0.01 (range 0–2). Drag to scale; hold shift for 1/100th detail."
  sigmaMin: "The noise level the schedule ends at, in unitless multiples of the latent's standard deviation. Range 0.001–0.5, and it must stay below σ MAX. Only the sigma shapes use it — MODEL and LOGSNR take λ MIN / λ MAX instead. Safe value: 0.01. Drag to scale; hold shift for 1/100th detail.",
  // handoff: "The noise level the schedule starts from, as a unitless multiple of the latent's own standard deviation. At 100 the start is effectively pure noise; below about 10 the sampler starts near the data, so more of the init audio survives. Beyond ~200 nothing changes except that steps are wasted denoising from further away. Ignored by rectified-flow objectives. Safe value: 100 (range 0–1000). Drag to scale; hold shift for 1/100th detail."
  sigmaMax: "The noise level the schedule starts from, as a unitless multiple of the latent's own standard deviation. Latent Forge reads it from the checkpoint rather than offering it as a free field: the render server reports the model's own σ MAX with the schedule and the graph is drawn from that. Shown here for reference.",
  stepped: "Quantises the chosen shape into plateaus: sigma is held for several steps, then jumps down. The shape still decides where the plateaus sit, so this stacks on geometric, log, logSNR and the rest. Safe value: off.",
  tilt: "How much of its own span each plateau still travels. At 0 the plateaus are perfectly flat, which is a no-op on the ODE samplers — dt is zero, so DPM++ and friends spend a forward pass and change nothing. Under ping-pong a flat plateau is instead a churn step: the model re-noises to the same level and gets a second look, correcting earlier errors at the cost of some smoothing. A small tilt keeps every step doing work. Safe value: 0.15. Drag to scale.",
  plateaus: "How many plateaus the stepped schedule holds. Each plateau repeats one noise level for several steps, then jumps down. Safe value: 6. Drag to scale.",
  rescale: "CFG rescale amount (scale_phi): pulls the guided prediction's scale back toward the unguided one, which tames the over-bright result of a high CFG. 0 disables it. Shown as the dotted line on the sigma graph. Safe value: 0.00.",
  latentNormalise: "Renormalises the mixed latent to the distribution the decoder expects. Mixing two latents shrinks their norm, so leaving this off tends to give a quiet, dull decode. Safe value: on.",

  // --- controls this build has that the drawing did not (spec §9.4).
  transportPlay: "Play or pause the arrangement from the playhead. Space does the same from anywhere outside a text field. Preview playback in the render container is separate: starting one stops the other.",
  transportStop: "Stop and leave the playhead where it is. Home rewinds it to zero.",
  transportLoop: "Loop the marked region instead of running on to the end of the arrangement — the fastest way to hear whether a join actually lands.",
  darkToggle: "Light or dark ground. The choice is kept in this browser. Canvases read their colours from the theme, so the waveforms, the ruler and the sigma graph follow it too.",
  filmTarget: "The value the FiLM head steers this lane toward, in onsets per second. The GAIN beside it scales how hard the conditioning is applied. Safe value: 4.0.",
  opSelect: "What RENDER does with the selected clip: A2A re-noises and re-denoises it at the noise amount above, DECODE just runs its latent back through the decoder, BEND applies the latent operations. The prompt and settings in this pane belong to whichever op is chosen.",
  previewMixdownToggle: "A/B the audio-domain preview mix against the committed mixdown. PREVIEW is what the timeline sounds like now; MIXDOWN is what the server actually rendered. They should agree — where they do not, the commit changed something the preview cannot see.",
  mixdownCommit: "Mixes the four lanes in the latent domain and decodes the result — the commit that turns the arrangement into audio. While it samples, the window border runs a C64 loader raster bar whose sweep rate falls with the remaining step count.",
  mixdownWave: "The latest mixdown. Click to scrub it, and drag it onto a lane to use it as a clip. Earlier mixdowns stay in the render history at the bottom of the screen.",
  previewRender: "Renders the current target with the settings in this pane. The result lands here to be auditioned; drag it onto a lane if you want it.",
  previewHistory: "Every render of this session, newest first. Loading one plays it here — it does not change the settings in this pane.",
  previewDragToLane: "Drag the previewed render onto a lane to add it as a clip at the drop position.",
  previewUseSettings: "Copies the settings the previewed render was made with into the current target. Loading a render from HISTORY never does this on its own.",
  previewReplaceClip: "Swaps the selected clip's audio for the previewed render, keeping the previous audio in the clip's history. Enabled only when the render was made from that clip.",
  latchToggle: "Turns LatCH guidance on for this lane. Both slots keep their settings while off; nothing is unloaded. Safe value: off.",
  filmToggle: "Turns the FiLM density adapter on for this lane. Safe value: off.",
  filmPreset: "Module preset — recalls just this FiLM slot's settings.",
  filmScale: "How hard the FiLM conditioning is applied, scaling the head's own default gain. Safe value: 1.75, the server's default.",
  loraToggle: "Turns the resident LoRA/DORA adapter on for this lane. Safe value: off.",
  loraPreset: "Module preset — recalls just this LoRA/DORA slot's settings.",
  loraModel: "Which adapter to apply. Resident slots (already loaded, from /slots) are listed first because switching to one is instant; anything else is loaded from disk on first use.",
  loraScale: "Adapter strength. Safe value: 1.0.",
  bungeeToggle: "Turns Bungee pitch-shifting on for this lane, applied during the Bungee stage before re-encoding. Safe value: off.",
  bungeePreset: "Module preset — recalls just this Bungee slot's settings. Undrawn in the handoff; the level exists in the frozen preset contract (spec §9.3, §6.3's level enum), so it needs a place to live.",
  filmCkpt: "Which FiLM checkpoint this lane uses. Server default is whatever /info reports as the film default; anything else is loaded from the film model root on first use.",
  modulePresetSave: "Saves this module's current settings, on/off state included, as a module preset -- under the selected name, or a new one you are asked for. Recall applies to the active lane only.",
  modulePresetDelete: "Deletes the selected module preset from the server. The lane's current settings are not changed.",
  masterLatchToggle: "Turns LatCH steering on for the mixed latent, after the lane chains. Safe value: off.",
  masterLatchHeadLabel: "Which head steers the mixed latent (spec §8.1 S8 -- the existing /steer math).",
  masterHead: "The LatCH head applied to the mix. Uses the same registry as the lane chains' slots.",
  masterGain: "How hard the head's gradient is applied to the mixed latent. Safe value: 64.",
  mixQuadWeight: "This lane's share of the weighted 4-way mix. All four are renormalised together; leaving every one at zero mixes the lanes equally.",
  mixLerp: "Linear interpolation between this node's two inputs.",
  mixSlerp: "Spherical interpolation between this node's two inputs -- the default, since SAME's latent space is strongly anisotropic and a straight lerp can cut through low-energy regions a slerp arcs around.",
  filesRoot: "Which server root to browse: crops (extracted latents), renders (past commits) or uploads (files dropped or picked from disk). An unmounted root is listed, greyed, rather than hidden.",
  filesFilter: "Filters the file list by substring match on its path. Clears to show every file under the selected root again.",
  masterPresetSave: "Saves the current master slice under the highlighted name, or asks for a new one if nothing is named yet. Recall replaces the whole slice (spec §9.3): every lane chain, clip layout, mix order and node values, master chain, sampling schedule and default prompt.",
  sessionSave: "Saves the whole project to the server under the selected session name, or asks for a name while it is still unsaved. After that, every change autosaves to it 2 s later.",
  sessionImportV1: "Opens a project file from disk. A v1 file from the old app is converted (lanes renamed LANE 1-4, missing settings filled with defaults); it stays unsaved until you SAVE it.",
  mixdownButton: "Mixes the four lanes in the latent domain and decodes the result — the commit that turns the arrangement into audio. While it samples, the window border runs a C64 loader raster bar whose sweep rate falls with the remaining step count.",
};
